### PR TITLE
Swift package manager support

### PR DESCRIPTION
**Pull request by michaelhenry**

### CODE REVIEW

**Comment by TimOliver** [comment]
Uh. Thanks for submitting a PR with an empty comment Michael. 😅

No moving the headers please. Please use symlinks instead. Thanks!

**Comment by michaelhenry** [comment]
@TimOliver oh sorry, forgot to include a description 🙇🏻‍♂️ .I will update this. Thanks

**Comment by michaelhenry** [comment]
@TimOliver It's now updated. please check when you have time. thank you 🙇🏻‍♂️

**Comment by TimOliver** [comment]
Haha no worries! Perfect! Thanks for that! :)

**Comment by michaelhenry** [comment]
@TimOliver thanks

**Pull request merged**
